GET http://localhost:3333/items

###

GET http://localhost:3333/items/608961da2cb0fb3b5416c0d7

###

DELETE http://localhost:3333/items/60a5d533527c813c909b57c0

###


PUT http://localhost:3333/items/60701bc814bd21513801a69b
Content-Type: application/json

{
  "name": "The Amazing X-Man"
}

###

POST http://localhost:3333/items
Content-Type: application/json

{
  "name": "Tatoo Tada",
  "desc": "xa",
  "qty": 89
}

###

POST http://localhost:3333/products
Content-Type: application/json

{
  "title": "IPhone XS Max 128",
  "description": "fake",
  "price": 1200.00
}

###
GET http://localhost:3333/products
